### ISSUE TITLE
TS2339 Property 'where' does not exist on type 'QueryBuilder

### ISSUE THREAD

**Issue by justinpenguin45** [Felipe-BP/nestjs-knex#8]
I get this error, however everything seems to appear working

Code snippet that causes the error

Property 'where' does not exist on type 'QueryBuilder<User, DeferredKeySelection<User, never, false, {}, false, {}, never>[]>'.
        const users = await this.knex
           .table<User>('user')
  >       .where('is_deleted', true)
            ^^^^^
          .andWhere('id', '>', 1);
        return users;
      }

**Comment by Felipe-BP** [comment]
Hello @justinpenguin45 thanks for the issue report and apologize for the delayed response.

I've just added an example trying to reproduce your scenario. You can check out [here](https://github.com/Felipe-BP/nestjs-knex/blob/develop/src/nestjs-knex-client/nestjs-knex-client.controller.ts).

I got no type checking errors, everything works well. Could you provide more context?

**Comment by Felipe-BP** [comment]
I'll close it for now, if you have any other question you can open a new thread!
